### ISSUE TITLE
Service格式化后分配任务失败

### ISSUE THREAD

**Issue by xx-zhang** [xx-scan/xx-scan#7]
错误 recode 格式化错误
```
Traceback (most recent call last):
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`xxscan`.`scan_recode`, CONSTRAINT `scan_recode_service_id_244c1385_fk_host_services_id` FOREIGN KEY (`service_id`) REFERENCES `host_services` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django/xs_venv/lib64/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/django/xx-scan/apps/scan/tasks.py", line 108, in recodes_and_run
    recodes = collect_recodes(scheme_id=scan_schemeid, workspaceid=workspaceid)
  File "/home/django/xx-scan/apps/scan/api/mudules/scan_v2/recode.py", line 43, in collect_recodes
    [x.save() for x in recodes]
  File "/home/django/xx-scan/apps/scan/api/mudules/scan_v2/recode.py", line 43, in <listcomp>
    [x.save() for x in recodes]
  File "/home/django/xx-scan/apps/scan/models/scan_cfg.py", line 150, in save
    super(ScanRecode, self).save(*args, **kwargs)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`xxscan`.`scan_recode`, CONSTRAINT `scan_recode_service_id_244c1385_fk_host_services_id` FOREIGN KEY (`service_id`) REFERENCES `host_services` (`id`))')
```

**Comment by xx-zhang** [comment]
很久前已经修复
